"""empty message

Revision ID: bdff415e2569
Revises: 
Create Date: 2026-03-10 22:39:28.133687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdff415e2569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_id'), 'faculties', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECTOR', 'DEAN', 'HEAD_TEACHER', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_method', sa.Enum('OTP', 'TOTP', name='mfamethod'), nullable=False),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'number', name='uq_semester_course_number')
    )
    op.create_index(op.f('ix_semesters_course_id'), 'semesters', ['course_id'], unique=False)
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('is_expelled', sa.Boolean(), nullable=False),
    sa.Column('expulsion_reason', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('study_directions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_directions_faculty_id'), 'study_directions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_study_directions_id'), 'study_directions', ['id'], unique=False)
    op.create_table('curricula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_direction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curricula_id'), 'curricula', ['id'], unique=False)
    op.create_index(op.f('ix_curricula_study_direction_id'), 'curricula', ['study_direction_id'], unique=False)
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_direction_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplines_department_id'), 'disciplines', ['department_id'], unique=False)
    op.create_index(op.f('ix_disciplines_id'), 'disciplines', ['id'], unique=False)
    op.create_index(op.f('ix_disciplines_study_direction_id'), 'disciplines', ['study_direction_id'], unique=False)
    op.create_table('study_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_direction_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_groups_course_id'), 'study_groups', ['course_id'], unique=False)
    op.create_index(op.f('ix_study_groups_id'), 'study_groups', ['id'], unique=False)
    op.create_index(op.f('ix_study_groups_study_direction_id'), 'study_groups', ['study_direction_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('academic_degree', sa.String(), nullable=True),
    sa.Column('academic_title', sa.String(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('is_fired', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_department_id'), 'teachers', ['department_id'], unique=False)
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=True)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('credit_date', sa.Date(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'discipline_id', 'semester_id', 'attempt_number', name='uq_credit_student_discipline_semester_attempt')
    )
    op.create_index(op.f('ix_credits_discipline_id'), 'credits', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_index(op.f('ix_credits_semester_id'), 'credits', ['semester_id'], unique=False)
    op.create_index(op.f('ix_credits_student_id'), 'credits', ['student_id'], unique=False)
    op.create_index(op.f('ix_credits_teacher_id'), 'credits', ['teacher_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_value', sa.Enum('EXCELLENT', 'GOOD', 'SATISFACTORY', 'UNSATISFACTORY', 'PASS', 'FAIL', name='gradevalue'), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.CheckConstraint("grade_value IN ('EXCELLENT', 'GOOD', 'SATISFACTORY', 'UNSATISFACTORY', 'PASS', 'FAIL')", name='check_exam_grade_value'),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'discipline_id', 'semester_id', 'attempt_number', name='uq_exam_student_discipline_semester_attempt')
    )
    op.create_index(op.f('ix_exams_discipline_id'), 'exams', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_semester_id'), 'exams', ['semester_id'], unique=False)
    op.create_index(op.f('ix_exams_student_id'), 'exams', ['student_id'], unique=False)
    op.create_index(op.f('ix_exams_teacher_id'), 'exams', ['teacher_id'], unique=False)
    op.create_table('gradebooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_type', sa.Enum('EXAM', 'CREDIT', 'COURSEWORK', 'TEST', name='gradetype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'study_group_id', 'discipline_id', 'teacher_id', name='uq_gradebook_semester_group_discipline_teacher')
    )
    op.create_index(op.f('ix_gradebooks_discipline_id'), 'gradebooks', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_id'), 'gradebooks', ['id'], unique=False)
    op.create_index(op.f('ix_gradebooks_semester_id'), 'gradebooks', ['semester_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_study_group_id'), 'gradebooks', ['study_group_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_teacher_id'), 'gradebooks', ['teacher_id'], unique=False)
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'study_group_id', name='uq_student_study_group')
    )
    op.create_index(op.f('ix_student_groups_id'), 'student_groups', ['id'], unique=False)
    op.create_index(op.f('ix_student_groups_student_id'), 'student_groups', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_groups_study_group_id'), 'student_groups', ['study_group_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gradebook_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade_value', sa.Enum('EXCELLENT', 'GOOD', 'SATISFACTORY', 'UNSATISFACTORY', 'PASS', 'FAIL', name='gradevalue'), nullable=False),
    sa.Column('grade_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gradebook_id'], ['gradebooks.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gradebook_id', 'student_id', name='uq_grade_gradebook_student')
    )
    op.create_index(op.f('ix_grades_gradebook_id'), 'grades', ['gradebook_id'], unique=False)
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_gradebook_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_student_groups_study_group_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_student_id'), table_name='student_groups')
    op.drop_index(op.f('ix_student_groups_id'), table_name='student_groups')
    op.drop_table('student_groups')
    op.drop_index(op.f('ix_gradebooks_teacher_id'), table_name='gradebooks')
    op.drop_index(op.f('ix_gradebooks_study_group_id'), table_name='gradebooks')
    op.drop_index(op.f('ix_gradebooks_semester_id'), table_name='gradebooks')
    op.drop_index(op.f('ix_gradebooks_id'), table_name='gradebooks')
    op.drop_index(op.f('ix_gradebooks_discipline_id'), table_name='gradebooks')
    op.drop_table('gradebooks')
    op.drop_index(op.f('ix_exams_teacher_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_student_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_semester_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_discipline_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_credits_teacher_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_student_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_semester_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_discipline_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_department_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_study_groups_study_direction_id'), table_name='study_groups')
    op.drop_index(op.f('ix_study_groups_id'), table_name='study_groups')
    op.drop_index(op.f('ix_study_groups_course_id'), table_name='study_groups')
    op.drop_table('study_groups')
    op.drop_index(op.f('ix_disciplines_study_direction_id'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_id'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_department_id'), table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_index(op.f('ix_curricula_study_direction_id'), table_name='curricula')
    op.drop_index(op.f('ix_curricula_id'), table_name='curricula')
    op.drop_table('curricula')
    op.drop_index(op.f('ix_study_directions_id'), table_name='study_directions')
    op.drop_index(op.f('ix_study_directions_faculty_id'), table_name='study_directions')
    op.drop_table('study_directions')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_course_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_faculties_id'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
