"""Create university tables

Revision ID: 2026_03_10_0000
Revises: 6d330c3722d5
Create Date: 2026-03-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_03_10_0000'
down_revision: Union[str, None] = '6d330c3722d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Faculties
    op.create_table('faculties',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('short_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_id'), 'faculties', ['id'], unique=False)
    
    # Departments
    op.create_table('departments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('faculty_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('short_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    
    # Study directions
    op.create_table('study_directions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('faculty_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_directions_id'), 'study_directions', ['id'], unique=False)
    op.create_index(op.f('ix_study_directions_faculty_id'), 'study_directions', ['faculty_id'], unique=False)
    
    # Disciplines
    op.create_table('disciplines',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('study_direction_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('hours', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplines_id'), 'disciplines', ['id'], unique=False)
    op.create_index(op.f('ix_disciplines_study_direction_id'), 'disciplines', ['study_direction_id'], unique=False)
    op.create_index(op.f('ix_disciplines_department_id'), 'disciplines', ['department_id'], unique=False)
    
    # Curricula
    op.create_table('curricula',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('study_direction_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curricula_id'), 'curricula', ['id'], unique=False)
    op.create_index(op.f('ix_curricula_study_direction_id'), 'curricula', ['study_direction_id'], unique=False)
    
    # Courses
    op.create_table('courses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    
    # Semesters
    op.create_table('semesters',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('start_date', sa.String(), nullable=False),
        sa.Column('end_date', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'number', name='uq_semester_course_number')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_index(op.f('ix_semesters_course_id'), 'semesters', ['course_id'], unique=False)
    
    # Study groups
    op.create_table('study_groups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('study_direction_id', sa.Integer(), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['study_direction_id'], ['study_directions.id'], ),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_groups_id'), 'study_groups', ['id'], unique=False)
    op.create_index(op.f('ix_study_groups_study_direction_id'), 'study_groups', ['study_direction_id'], unique=False)
    op.create_index(op.f('ix_study_groups_course_id'), 'study_groups', ['course_id'], unique=False)
    
    # Students
    op.create_table('students',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('middle_name', sa.String(), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=False),
        sa.Column('enrollment_year', sa.Integer(), nullable=False),
        sa.Column('is_expelled', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('expulsion_reason', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=False)
    
    # Teachers
    op.create_table('teachers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('middle_name', sa.String(), nullable=True),
        sa.Column('position', sa.String(), nullable=False),
        sa.Column('academic_degree', sa.String(), nullable=True),
        sa.Column('academic_title', sa.String(), nullable=True),
        sa.Column('hire_date', sa.Date(), nullable=False),
        sa.Column('is_fired', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('description', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    op.create_index(op.f('ix_teachers_department_id'), 'teachers', ['department_id'], unique=False)
    
    # Student groups (many-to-many)
    op.create_table('student_groups',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('study_group_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default='true'),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'study_group_id', name='uq_student_study_group')
    )
    op.create_index(op.f('ix_student_groups_id'), 'student_groups', ['id'], unique=False)
    op.create_index(op.f('ix_student_groups_student_id'), 'student_groups', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_groups_study_group_id'), 'student_groups', ['study_group_id'], unique=False)
    
    # Grade types enum
    gradetype_enum = sa.Enum('EXAM', 'CREDIT', 'COURSEWORK', 'TEST', name='gradetype')
    gradetype_enum.create(op.get_bind())
    
    # Grade values enum
    gradevalue_enum = sa.Enum('5', '4', '3', '2', 'PASS', 'FAIL', name='gradevalue')
    gradevalue_enum.create(op.get_bind())
    
    # Gradebooks
    op.create_table('gradebooks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('semester_id', sa.Integer(), nullable=False),
        sa.Column('study_group_id', sa.Integer(), nullable=False),
        sa.Column('discipline_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('grade_type', gradetype_enum, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('created_at', sa.Date(), nullable=False),
        sa.Column('is_closed', sa.Boolean(), nullable=False, server_default='false'),
        sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
        sa.ForeignKeyConstraint(['study_group_id'], ['study_groups.id'], ),
        sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('semester_id', 'study_group_id', 'discipline_id', 'teacher_id', name='uq_gradebook_semester_group_discipline_teacher')
    )
    op.create_index(op.f('ix_gradebooks_id'), 'gradebooks', ['id'], unique=False)
    op.create_index(op.f('ix_gradebooks_semester_id'), 'gradebooks', ['semester_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_study_group_id'), 'gradebooks', ['study_group_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_discipline_id'), 'gradebooks', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_gradebooks_teacher_id'), 'gradebooks', ['teacher_id'], unique=False)
    
    # Grades
    op.create_table('grades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('gradebook_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('grade_value', gradevalue_enum, nullable=False),
        sa.Column('grade_date', sa.Date(), nullable=False),
        sa.Column('comment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['gradebook_id'], ['gradebooks.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('gradebook_id', 'student_id', name='uq_grade_gradebook_student')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_gradebook_id'), 'grades', ['gradebook_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    
    # Credits
    op.create_table('credits',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('discipline_id', sa.Integer(), nullable=False),
        sa.Column('semester_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('is_passed', sa.Boolean(), nullable=False),
        sa.Column('credit_date', sa.Date(), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('comment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
        sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'discipline_id', 'semester_id', 'attempt_number', name='uq_credit_student_discipline_semester_attempt')
    )
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_index(op.f('ix_credits_student_id'), 'credits', ['student_id'], unique=False)
    op.create_index(op.f('ix_credits_discipline_id'), 'credits', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_credits_semester_id'), 'credits', ['semester_id'], unique=False)
    op.create_index(op.f('ix_credits_teacher_id'), 'credits', ['teacher_id'], unique=False)
    
    # Exams
    op.create_table('exams',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('discipline_id', sa.Integer(), nullable=False),
        sa.Column('semester_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('grade_value', gradevalue_enum, nullable=False),
        sa.Column('exam_date', sa.Date(), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('comment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
        sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('student_id', 'discipline_id', 'semester_id', 'attempt_number', name='uq_exam_student_discipline_semester_attempt'),
        sa.CheckConstraint("grade_value IN ('5', '4', '3', '2')", name='check_exam_grade_value')
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_student_id'), 'exams', ['student_id'], unique=False)
    op.create_index(op.f('ix_exams_discipline_id'), 'exams', ['discipline_id'], unique=False)
    op.create_index(op.f('ix_exams_semester_id'), 'exams', ['semester_id'], unique=False)
    op.create_index(op.f('ix_exams_teacher_id'), 'exams', ['teacher_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams')
    op.drop_table('credits')
    op.drop_table('grades')
    op.drop_table('gradebooks')
    op.drop_table('student_groups')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('study_groups')
    op.drop_table('semesters')
    op.drop_table('courses')
    op.drop_table('curricula')
    op.drop_table('disciplines')
    op.drop_table('study_directions')
    op.drop_table('departments')
    op.drop_table('faculties')
    
    # Drop enums
    sa.Enum(name='gradevalue').drop(op.get_bind())
    sa.Enum(name='gradetype').drop(op.get_bind())
    # ### end Alembic commands ###
